### ISSUE TITLE
Make List#__unlink_node public

### ISSUE THREAD

**Issue by nex3** [spectator/linked-list#5]
There's currently no way to remove a value from a list in O(1) time, even if you have its `Node`. Exposing `List#__unlink_node` publicly, or alternately giving `List#delete` a special case if it's passed a `Node`, would solve this.

**Comment by spectator** [comment]
Hi @nex3 , thank you for bringing this up! Would you be able to work on a pull request? I like your suggestion to make `List#delete` being able to handle `Node` objects.
